kind: pipeline
name: default-1

steps:
- name: frontend
  image: node
  commands:
  - npm install
  

- name: test
  image: node
  commands:
  - env
--- 
kind: pipeline
name: default-2

steps:
- name: frontend
  image: node
  commands:
  - npm install
  

- name: test
  image: node
  commands:
  - env
 
